### PR TITLE
Added bash and fish shell completions

### PR DESCRIPTION
**Pull request by SanskritFritz**
I'm certainly not sure whether you like the folder structure, I just copied it from borg.
Also I realised that ```qk ls``` is rather too fancy for scripting, I had to use
```qk ls | grep '^| ' | cut -d ' ' -f 2 | tail -n '+2'```
for a simplified output. Could you maybe consider adding a --simple option to the ls command?

### CODE REVIEW

**Comment by SanskritFritz** [comment]
Hmm, I tried to rebase squash the top 2 commits but this is the result. I'll send a completely new PR when we have discussed the changes here.

**Comment by bostrt** [comment]
Hi @SanskritFritz,

Thanks for submitting this! I'm curious if we can use the bash completion functionality shipped with Click:

  https://click.palletsprojects.com/en/7.x/bashcomplete/

It would require some code additions but we wouldn't have to maintain a separate bash completion file. 

Let me know what you think!

**Comment by SanskritFritz** [comment]
I didn't know about that functionality in Click (and I never used Click anyway). I've read that page you linked and I think it sounds awesome. Also this way we get zsh tab completions as well for free!
I would love to maintain the fish tab completions further on just as I do with borg backup.

**Comment by bostrt** [comment]
Awesome, I will test the completion setup using Click some this week and update you again if I think it will work out fine. 

>  I would love to maintain the fish tab completions further on just as I do with borg backup.

Absolutely, I would really appreciate keeping the fish tab completion! If you would like to open another PR for just the fish completion, we can continue there.

**Comment by SanskritFritz** [comment]
Is there a need for a PR? You can just copy the file from this PR for your convenience. Having said that I'll certainly send a PR if it is more convenient for you.

**Comment by bostrt** [comment]
Certainly! I'll copy from here when I submit the other completion changes.

**Comment by SanskritFritz** [comment]
And maybe it is time to ask Click upstream to support Fish as well... :smile:

**Pull request closed without merging**
